module.exports = [
  { tag: "glowshine" },
  { tag: "gigi8" },
  { tag: "roelandp" },
  { tag: "netuoso" },
  { tag: "engrave" },
  { tag: "theycallmedan" },
  { tag: "blocktrades" },
  { tag: "pgarcgo" },
  { tag: "cervantes" },
  { tag: "leofinance" },
  { tag: "mindtrap" },
  { tag: "steem.leo" },
  { tag: "roadstories" },
  { tag: "johnvibes" },
  { tag: "victoriag" },
  { tag: "ecency" },
  { tag: "emsonic" },
  { tag: "pouchon" },
  { tag: "chekohler" },
  { tag: "flauwy" },
  { tag: "themarkymark" },
  { tag: "taskmaster4450" },
  { tag: "whoisjohn" },
  { tag: "perceval" },
  { tag: "wartrapa" },
  { tag: "actifit"},
  { tag: "bengy"},
  { tag: "azircon"},
  { tag: "saffisara"},
  { tag: "animal-shelter"},
  { tag: "threespeak"},
  { tag: "elenasteem"},
  { tag: "riverflows"},
  { tag: "krnel"},
  { tag: "edicted"},
  { tag: "oflyhigh"},
];
